### ISSUE TITLE
Remove default horizontal paddings

### ISSUE THREAD

**Issue by Astanusic** [FelixKratz/yabai#13]
Hello, first of all thanks for this fork, it run super smooth on my ventura.

I was wondering if there is a way to remove the default padding left and right ?
Ive changed it in my yabairc but it seems its getting overwrite somewhere: when I switch layout mode or if a new app window is openned I got huge paddings on horizontal sides.

**Comment by FelixKratz** [comment]
It is this commit, I use the auto padding on my ultrawide display and have hardcoded the optimal windows width and height. If you simply remove this patch it should be gone:
https://github.com/FelixKratz/yabai/commit/030fac4f770227e2ef420b8fe9ebd309af811c7e

**Comment by Astanusic** [comment]
Sorry if it sounds stupid but what is the cleanest way to revert ?
Should I uninstall, fork and reinstall ?

**Comment by FelixKratz** [comment]
If you create your own homebrew-formulae repo like mine: https://github.com/FelixKratz/homebrew-formulae
You will be able to tap it and install your own forks directly via brew. Thats the way I do it for all the forks I am using. Just make sure to use a different name for the formulas of your forks, otherwise brew will be unhappy. Thats why my yabai fork is called fyabai.

**Comment by Astanusic** [comment]
Alright, thanks for your time and your work.
