### ISSUE TITLE
Break when set layout as bsp

### ISSUE THREAD

**Issue by albert-ying** [FelixKratz/yabai#6]
Hi, I updated to the head to play with the new animation function. However, the new version breaks when running
```
yabai -m config layout                       bsp
```

```
❯ yabai
'window_opacity_duration' cannot be changed on macOS Catalina/Big Sur/Monterey because of an Apple bug in the WindowServer
unknown key 'active_window_opacity'
unknown key 'normal_window_opacity'
[1]    6881 trace trap  yabai
```

The previous version works fine to me tho

**Comment by albert-ying** [comment]
Hmm I just tried to install it from the head, still getting the same error

**Comment by FelixKratz** [comment]
Did you also reinstall the sa?

**Comment by albert-ying** [comment]
Yes, I did. I'm on M1 Mac, is it related to that?

**Comment by FelixKratz** [comment]
I am on M1 as well, so no. Unfortunately you will have to look for the problem yourself, I am only maintaining this fork for experimenting and for myself and it is highly unstable because I force push to it frequently. I would suggest you to fork the main yabai repo and cherry-pick features you like to that fork, while looking through the changes I have made so you are able to maintain your own fork.

**Comment by albert-ying** [comment]
Yeah, I just tried to enable it, it works!! Thank you so much!
